### ISSUE TITLE
Use git instead of find

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-travis#56]
In lots of cases, we can limit our searching to files known to git and avoid a lot
of pruning with git ls-files and git grep

i.e.

```
# Find shell scripts
$> git grep -P -l '#!/bin/(ba)?sh'
```

```
# Find MarkDown files
$> git ls-files | grep \\.md  | grep -v CHANGELOG.md
```

**Comment by limed** [comment]
I feel that we should keep using `find` the scenario here would be that if someone is starting a new project and have not `git init` their repository and just wanted to make sure that everything is linted correctly before even committing and pushing

**Comment by tinnightcap** [comment]
I agree with limed on this one. I am going to leave the find in place for now and close this and the associated PR out.
